[package]
name = "bitcoin-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
hmac = "0.12.1"
ibig = "0.3.6"
sha2 = "0.10.8"
thiserror = "1.0"
hex = "0.4.3"
